version: "3.7"

services:
  egun:
    image: localhost:5000/egun-bieter
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 4000:4000
    environment:
      SECRET_KEY_BASE: m+yIxtaDJnRxxW31c063pZ1IdOBiW/3HyIyevE5LTfCI4asts7H8p9332bbO+Jrd